import { test, expect } from "@playwright/test";
import { mkdirSync } from "node:fs";

const url=process.env.COALITION_E2E_URL,token=process.env.COALITION_OPERATOR_TOKEN;
test.skip(!url||!token,"Requires isolated fixture API/worker/PostgreSQL stack.");
test("negotiated stack: edited budget, genuine fixture workflow, lower receipt and refresh",async({page,request},info)=>{
  test.setTimeout(150000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  const headers={"X-Coalition-Request":"1","X-Operator-Token":token!,Origin:url!};
  async function op(path:string,body?:unknown){const r=await request.fetch("/api/operator"+path,{method:body===undefined?"GET":"POST",data:body,headers});expect(r.ok(),await r.text()).toBeTruthy();return r.json();}
  expect((await (await request.get('/api/config')).json()).mode).toBe('fixture');
  const run=await op('/runs',{profile:'small',scenario:'success',close_seconds:90});
  await page.goto(run.judge_url);
  await page.getByRole('link',{name:'Merchant widget'}).click();
  await expect(page.getByRole('heading',{name:'Cabin One',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Evaluate this product with your requirements'}).click();
  await expect(page.getByText('Merchant entry: Cabin One · Graphite · one unit.')).toBeVisible();
  await page.getByRole('button',{name:'Find compatible offers'}).click();
  await expect(page.getByLabel('Maximum delivered total · USD')).toBeVisible();
  await page.getByLabel('Maximum delivered total · USD').fill('86');
  await page.getByRole('button',{name:'Re-evaluate edited requirements'}).click();
  await expect(page.getByRole('button',{name:'Negotiate selected offer'})).toBeDisabled();
  await page.getByLabel('Maximum delivered total · USD').fill('100');
  await page.getByRole('button',{name:'Re-evaluate edited requirements'}).click();
  await expect(page.getByRole('button',{name:'Negotiate selected offer'})).toBeEnabled();
  await page.getByRole('button',{name:'Negotiate selected offer'}).click();
  await expect(page.getByRole('heading',{name:'Accepted quote · version 1'})).toBeVisible({timeout:20000});
  await expect(page.getByText('Inventory reserved: 5 units',{exact:false})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  mkdirSync('../.impeccable/review',{recursive:true});
  await page.screenshot({path:`../.impeccable/review/negotiated-${info.project.name}.png`,fullPage:true});
  await op('/runs/'+run.run_id+'/fixture-prepare',{});
  await expect.poll(async()=>{const e=await op('/runs/'+run.run_id);return e.buyers.filter((b:any)=>b.admitted).length;},{timeout:20000}).toBe(4);
  await op('/runs/'+run.run_id+'/activate',{});
  await page.getByRole('link',{name:'Review exact terms & checkout'}).click();
  await page.getByRole('checkbox').first().check();
  await page.getByRole('button',{name:'Simulate $89 authorization'}).click();
  await expect(page.getByText('5 of 5 committed')).toBeVisible({timeout:20000});
  await expect(page.getByText('Your place is confirmed.')).toBeVisible();
  await page.reload();
  await expect(page.getByText('Your place is confirmed.')).toBeVisible();
  await expect(page.getByRole('region',{name:'Payment receipt'})).toBeVisible({timeout:110000});
  await expect(page.getByText('Paid $85.00 USD')).toBeVisible();
  await expect(page.getByRole('region',{name:'Payment receipt'}).getByText('$4',{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByText('Paid $85.00 USD')).toBeVisible();
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>[".checkout-summary",".checkout-payment"].every(s=>getComputedStyle(document.querySelector(s)!).opacity==="1"));
  await page.screenshot({path:`../.impeccable/review/negotiated-receipt-${info.project.name}.png`,fullPage:true});
  await expect(page.getByRole('region',{name:'Payment receipt'})).toBeVisible();
  expect(errors).toEqual([]);
});
