import { useEffect, useRef, useState } from "react";
import { useReducedMotion } from "motion/react";
import catalog from '../../catalog.json';
import { api, money, type Config, type Product, type Status, type Terms } from "./api";
import Icon from './components/Icon';
import ProductPhoto from './components/ProductPhoto';
import { AnimatedBeam } from "./components/magicui/animated-beam";
import { AnimatedList } from "./components/magicui/animated-list";
import { NumberTicker } from "./components/magicui/number-ticker";

interface Constraints { max_total_minor: number | null; latest_arrival: string | null; required_features: string[]; device: string | null; flexibility: string[] }
interface Assessment { product_id: string; eligible: boolean; available: number; requirements: { requirement: string; verdict: string; rationale: string; source: string }[] }
interface Journey {
  request: { id: string; raw_text: string; status: string; constraints: Constraints | null; error: string | null; error_kind?: string; clarification?: {fields: string[]; question: string} | null } | null;
  assessments: Assessment[];
  negotiation: { id: string; status: string; error: string | null } | null;
  rounds: { id: number; role: string; valid: boolean; public_summary: string }[];
  group: { id: string; run_id: string; profile: string; status: string };
  availability?: string;
  status: Status | null; eligible: boolean; compatible_count: number; products: Product[];
}
const initial = 'Noise-canceling headphones under $100 for my iPhone 12. I can wait a week.';
const headphones = (catalog as unknown as Product[]).filter(p=>p.category==='Headphones'&&p.catalog_active!==false);
export function displayDate(value: string | undefined) {
  const date=value?new Date(value):null;
  return date&&!Number.isNaN(date.getTime())?date.toLocaleString(undefined,{timeZone:'UTC',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}):null;
}
function StoreHeader({config,run}:{config:Config|null;run?:string}) {
  return <header className="shopping-header"><a href="/" className="shopping-wordmark" aria-label="Coalition home"><Icon name="logo" size={30}/>Coalition<span className="wordmark-period">.</span></a><nav aria-label="Main"><a href="/" aria-current={location.pathname==='/'?'page':undefined}>Shop</a><a href={'/purchases'+(run?'?run='+run:'')} aria-current={location.pathname==='/purchases'?'page':undefined}>My purchases</a></nav><details className="sandbox-badge"><summary>Sandbox demo</summary><div><strong>A demonstration of group purchasing</strong><p>{config?.mode==='connected'?'Simulated buyers and merchant offers. Live AI decisions. Real PayPal sandbox operations.':config?.mode==='fixture'?'Simulated buyers, offers, AI and payments. This is a fixture demo.':'Demo mode is being checked. No payment is requested while browsing.'}</p><p>Real product models and sourced photography. Merchant offers, prices and delivery are simulated; no physical fulfillment. Coalition is an independent sandbox demo.</p><a href="/how-group-pricing-works">How group pricing works</a></div></details></header>;
}
function StoreFooter() { return <footer className="shopping-footer"><span>Coalition · Shopping, together.</span><p>Real products · simulated merchant offers · sandbox purchases</p><a href="/how-group-pricing-works">How group pricing works</a></footer>; }
function FitDetails({assessment}:{assessment:Assessment}) {return <details className="fit-details"><summary>{assessment.eligible?'Why it fits':'Why it doesn’t fit'}</summary><ul>{assessment.requirements.map((r,i)=><li key={i} className={'verdict-'+r.verdict}><strong>{r.requirement}: {r.verdict==='yes'?'Meets requirement':r.verdict==='no'?'Does not meet requirement':'Unknown'}</strong><p>{r.rationale}</p><small>Source: {r.source}</small></li>)}</ul></details>;}

export default function RequestDeal() {
  const [config,setConfig]=useState<Config|null>(null),[data,setData]=useState<Journey|null>(null),[error,setError]=useState('');
  const [raw,setRaw]=useState(''),[edits,setEdits]=useState<Constraints|null>(null),[selected,setSelected]=useState(new URLSearchParams(location.search).get('product')||''),[busy,setBusy]=useState(false);
  const [beam,setBeam]=useState<string|false>(false);
  const container=useRef<HTMLDivElement>(null),buyer=useRef<HTMLSpanElement>(null),merchant=useRef<HTMLSpanElement>(null),previous=useRef<number|null>(null),input=useRef<HTMLInputElement>(null),requirements=useRef<HTMLDetailsElement>(null);
  const reduced=useReducedMotion();
  async function refresh(){const next=await api<Journey>('/journey');setData(next);return next;}
  async function boot(){try{const c=await api<Config>('/config');setConfig(c);const params=new URLSearchParams(location.search);const invite=new URLSearchParams(location.hash.slice(1)).get('invite')||params.get('invite');const s=await api<{run_id:string}>('/session',{run_id:params.get('run')||undefined,invite:invite||undefined,shopping:true});const url=new URL(location.href);url.searchParams.set('run',s.run_id);url.searchParams.delete('invite');if(invite)url.hash='';history.replaceState(null,'',url);const next=await refresh();if(invite&&next.group.profile==='legacy'){location.replace('/checkout?run='+s.run_id);return;}setError('');}catch{setError('Shopping is unavailable right now. Please try again.');}}
  useEffect(()=>{void boot();},[]);
  useEffect(()=>{if(!data)return;const active=['queued','running'].includes(data.request?.status||'')||['queued','running'].includes(data.negotiation?.status||'')||data.status&&!['SUCCEEDED','FAILED'].includes(data.status.group.status);const timer=setTimeout(()=>void refresh().catch(()=>setError('We couldn’t refresh your deal. Try again.')),active?2000:10000);return()=>clearTimeout(timer);},[data]);
  useEffect(()=>{if(data?.request){setRaw(data.request.raw_text);if(data.request.constraints)setEdits(data.request.constraints);}},[data?.request?.id,data?.request?.status]);
  useEffect(()=>{const match=data?.assessments.find(a=>a.product_id===data.status?.offer.product_id&&a.eligible)??data?.assessments.find(a=>a.eligible&&a.available>0);if(match&&!data?.assessments.some(a=>a.product_id===selected&&a.eligible&&a.available>0))setSelected(match.product_id);},[data?.assessments]);
  useEffect(()=>{const count=data?.rounds.length??0;if(previous.current!==null&&count>previous.current&&!reduced){const emitted=data?.rounds.slice(previous.current).filter(r=>r.valid&&r.public_summary.includes(': Proposed ')).at(-1);if(emitted)setBeam(emitted.role);}previous.current=count;const timer=setTimeout(()=>setBeam(false),800);return()=>clearTimeout(timer);},[data?.rounds.length,reduced]);
  const products=data?.products.length?data.products:headphones;
  const evaluating=busy||['queued','running'].includes(data?.request?.status||''),negotiating=['queued','running'].includes(data?.negotiation?.status||'');
  const failed=data?.request?.status==='failed';
  const clarification=data?.request?.status==='clarification';
  const closed=!!data?.status&&(data.availability?['settled','canceled','closed','unavailable'].includes(data.availability):data.group.status!=='OPEN'||Date.now()>=new Date(data.status.offer.close_at||data.status.group.deadline||'').getTime());
  const locked=!!data?.status?.commitment?.active;
  // A run's quote is a search result only when this completed request fits that exact headphone offer.
  const candidate=data?.status?.offer;
  const currentResult=!error&&!evaluating&&data?.request?.status==='completed'&&data.request.raw_text===raw&&JSON.stringify(edits)===JSON.stringify(data.request.constraints);
  const acceptedQuote=currentResult&&candidate?.pricing_model==='tiers'&&data.eligible&&products.some(p=>p.id===candidate.product_id)&&data.assessments.some(a=>a.product_id===candidate.product_id&&a.eligible)?candidate:null;
  const offer=acceptedQuote?.product_id===selected?acceptedQuote:null;
  const product=products.find(p=>p.id===selected);
  const assessment=currentResult?data.assessments.find(a=>a.product_id===product?.id):undefined;
  const count=acceptedQuote?data?.status?.confirmed_count??0:0,tiers=offer?.tier_schedule??[],nextTier=tiers.find(t=>t.minimum_buyers>count);
  const highest=tiers.length>0&&count>0&&count>=tiers[tiers.length-1].minimum_buyers;
  const matches=currentResult?data.assessments.filter(a=>a.eligible):[];
  const shown=currentResult&&matches.length?products.filter(p=>matches.some(a=>a.product_id===p.id)):products;
  async function evaluate(e?:React.FormEvent,text=raw){e?.preventDefault();setBusy(true);setError('');try{await api('/requests',{raw_text:text,edits:text===raw?edits||undefined:undefined});await refresh();}catch{setError('We couldn’t evaluate this request. Try again.');}finally{setBusy(false);}}
  async function negotiate(){requirements.current?.removeAttribute('open');setBusy(true);setError('');try{const result=await api<{run_id?:string}>('/negotiations',{product_id:selected});if(result.run_id){const url=new URL(location.href);url.searchParams.set('run',result.run_id);history.replaceState(null,'',url);}await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function findAnother(){setBusy(true);setError('');try{const result=await api<{run_id:string}>('/session',{shopping:true,new_deal:true});const url=new URL(location.href);url.searchParams.set('run',result.run_id);history.replaceState(null,'',url);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="shopping-page"><StoreHeader config={config} run={data?.group.run_id}/><main>
    <section className="shopping-search" aria-labelledby="shopping-title"><div><h1 id="shopping-title">Shop together. Pay less.</h1><p>Find the right headphones. Let the group do the bargaining.</p></div><form onSubmit={evaluate}><label htmlFor="shopping-query">What are you shopping for?</label><div className="shopping-search-field"><Icon name="search"/><input ref={input} id="shopping-query" placeholder="Noise-canceling headphones, under $100…" value={raw} required minLength={3} maxLength={1200} disabled={locked||negotiating||evaluating} onChange={e=>{setRaw(e.target.value);setEdits(null);}}/><button className="coalition-button" disabled={!data||locked||negotiating||evaluating}>{evaluating?'Finding deals…':'Find deals'}<Icon name="arrow" size={17}/></button></div></form>
      {!data?.request&&<button className="search-example" onClick={()=>{setRaw(initial);input.current?.focus();}}>Try: headphones under $100, delivered within a week <Icon name="arrow" size={14}/></button>}
      {edits&&<details open={clarification||undefined} ref={requirements} className="shopping-requirements"><summary>Your requirements · {edits.max_total_minor===null?'budget needed':money(edits.max_total_minor)+' maximum'}</summary><fieldset disabled={locked||negotiating||evaluating}><label>Maximum delivered total · USD<input type="number" min="0.01" max="10000" step="0.01" value={edits.max_total_minor===null?'':edits.max_total_minor/100} onChange={e=>{if(/^\d*(?:\.\d{0,2})?$/.test(e.target.value))setEdits({...edits,max_total_minor:e.target.value?Number(e.target.value.split('.')[0])*100+Number((e.target.value.split('.')[1]||'').padEnd(2,'0')):null});}}/></label><label>Latest arrival · UTC<input type="date" value={edits.latest_arrival||''} min={new Date().toISOString().slice(0,10)} onChange={e=>setEdits({...edits,latest_arrival:e.target.value||null})}/></label><label>Required device compatibility<input value={edits.device||''} maxLength={80} onChange={e=>setEdits({...edits,device:e.target.value||null})}/></label><div className="feature-edits">{edits.required_features.map((f,i)=><label key={f}><input type="checkbox" checked onChange={()=>setEdits({...edits,required_features:edits.required_features.filter((_,j)=>j!==i),flexibility:[...edits.flexibility,'Explicitly removed requirement: '+f]})}/>{f}<small>Uncheck to relax</small></label>)}<p>Flexibility: {edits.flexibility.length?edits.flexibility.join('; '):'None explicitly stated'}</p></div><button className="secondary-button" onClick={()=>void evaluate()}>Update deals</button></fieldset></details>}
    </section>
    {(failed||error)&&<div role="alert" className="shopping-error"><p>{failed?data?.request?.error_kind==='unsupported_requirements'?'This request is outside the supported offers. Edit your requirements.':data?.request?.error_kind==='provider_failure'?'Evaluation is unavailable. Your request is saved; try again.':data?.request?.error_kind==='invalid_model_output'?'The assessment could not be validated. Try again.':'We couldn’t evaluate this request. Try again.':error}</p><button onClick={()=>data?void evaluate():void boot()}>Try again</button></div>}
    {clarification&&<p role="status" className="shopping-wait">{data?.request?.clarification?.question} Complete your requirements above, then update deals.</p>}
    {(candidate||locked)&&<p className="saved-purchase"><button className="text-button" disabled={busy||negotiating} onClick={()=>void findAnother()}>Find another deal</button></p>}
    {closed&&<p role="status" className="shopping-wait">{data?.availability==='settled'?'This group has settled.':data?.availability==='canceled'?'This group is canceled.':data?.availability==='unavailable'?'This group has no available places.':'This group is closed.'} {data?.status?.commitment?'Your purchase record is saved.':'You have not joined this group.'}</p>}
    {locked&&<p className="saved-purchase"><a href={'/checkout?run='+data?.group.run_id}>View your saved purchase <Icon name="arrow" size={16}/></a></p>}
    {evaluating&&<p role="status" className="shopping-wait">Checking your needs against the product details…</p>}
    {product&&!failed&&!evaluating&&!error&&<section id="selected-product" className="shopping-selected" aria-labelledby="selected-heading"><ProductPhoto product={product}/><div className="shopping-purchase"><h2 id="selected-heading">{offer?'Your group deal':product.title}</h2>{offer&&<h3>{product.title}</h3>}<p className="product-variant">{offer?.variant||product.variants[0]} · {offer?.merchant||product.brand}</p><div className="shopping-price"><strong>{money(offer?.total_minor??product.price_minor)}</strong><span>{offer?'Maximum per person':'Sandbox list price'}</span></div>
      {offer?<><p className="lower-tier">{tiers.length>1?<>Could drop to <strong>{money(tiers[tiers.length-1].total_each_cents)}</strong> with {tiers[tiers.length-1].minimum_buyers} buyers.</>:'Group price fixed by the accepted deal.'}</p><p className="shopping-count"><Icon name="users" size={18}/><NumberTicker value={count}/> of {offer.capacity} payments authorized</p><progress aria-label="Verified authorization progress" value={count} max={offer.capacity}/><p className="progress-note">{nextTier?`${nextTier.minimum_buyers-count} more authorizations to reach ${money(nextTier.total_each_cents)}`:highest?'Highest tier reached. Final price is selected at closing.':'Waiting for authorizations.'}</p><ul className="shopping-logistics">{displayDate(offer.delivery_by)&&<li><Icon name="truck" size={18}/><span>Delivery by {displayDate(offer.delivery_by)}</span></li>}{displayDate(offer.close_at)&&<li><Icon name="clock" size={18}/><span>Closes {displayDate(offer.close_at)}</span></li>}<li><Icon name="check" size={18}/><span>{offer.capacity} units reserved · shipping included</span></li></ul><a className="coalition-button" href={'/checkout?run='+data!.group.run_id}>{data?.status?.commitment?'View purchase':closed?'View closed deal':'Review deal'}<Icon name="arrow" size={18}/></a></>:<><p className="product-description">{product.description}</p><p className="shopping-delivery"><Icon name="truck" size={18}/>{product.delivery_days}-day delivery · shipping included</p>{assessment?<><p className={'fit-label '+(assessment.eligible?'fit-yes':'fit-unknown')}>{assessment.eligible?assessment.available>0?'Fits your request':'Currently unavailable':assessment.requirements.some(r=>r.verdict==='unknown')?'A required feature is unknown':'Doesn’t meet your requirements'}</p><button className="coalition-button" disabled={!assessment.eligible||!assessment.available||negotiating||busy||locked} onClick={()=>void negotiate()}>{negotiating?'Finding your group price…':'Get group price'}<Icon name="arrow" size={17}/></button>{candidate&&<p className="progress-note">{acceptedQuote&&acceptedQuote.product_id!==product.id?<>This group is purchasing {acceptedQuote.title}. <button className="text-button" onClick={()=>setSelected(acceptedQuote.product_id)}>View group deal</button></>:'This group’s agreed product does not fit your updated request.'}</p>}</>:<button className="coalition-button" disabled={!data||locked||negotiating} onClick={()=>{if(raw.trim())void evaluate();else input.current?.focus();}}>Find a group deal<Icon name="arrow" size={17}/></button>}</>}
      {product.source_url&&<details className="fit-details"><summary>Product details</summary><ul>{product.features.map(feature=><li key={feature}>{feature}</li>)}</ul><a href={product.source_url} target="_blank" rel="noopener noreferrer">{product.brand} specifications <Icon name="arrow" size={14}/></a></details>}
      {assessment&&<FitDetails assessment={assessment}/>}
      {(negotiating||currentResult&&(data?.rounds.length||data?.negotiation?.status==='failed'))&&!failed&&<details className="shopping-negotiation" open={negotiating||data?.negotiation?.status==='failed'}><summary>{negotiating?'Finding your group price…':'How we got this price'}</summary><div ref={container} className="agent-connection"><span ref={buyer}>Buyer agent</span><span ref={merchant}>Merchant agent</span>{beam&&<AnimatedBeam containerRef={container} fromRef={buyer} toRef={merchant} reverse={beam==='merchant'} duration={.65} repeat={0} pathColor="transparent" gradientStartColor="#4338ca" gradientStopColor="#4338ca"/>}</div><p role="status">{negotiating?'Evaluating offer':data?.negotiation?.status==='failed'?'No agreement reached':'Merchant-approved group price'}</p><AnimatedList animate={!!beam}>{data?.rounds.map(r=><div key={r.id} className={'proposal-round '+r.role}><strong>{r.role==='buyer'?'Buyer agent':'Merchant agent'}</strong><p>{r.public_summary.replace(/^(Buyer|Merchant) agent: /,'')}</p></div>)}</AnimatedList>{data?.negotiation?.error&&<p>{data.negotiation.error}</p>}</details>}
    </div></section>}
    <section className="shopping-catalog" aria-labelledby="catalog-heading"><div className="shopping-section-heading"><h2 id="catalog-heading">{matches.length?'Deals that fit your request':'Explore headphones'}</h2><span>{shown.length} products</span></div>{currentResult&&!matches.length&&<p className="no-matches">No offers meet all your requirements. Edit your requirements to try again.</p>}<ul className="shopping-grid">{shown.map(p=>{const a=currentResult?data.assessments.find(a=>a.product_id===p.id):undefined;const accepted=acceptedQuote?.product_id===p.id;return <li key={p.id}><button className="product-browse" aria-label={'Explore '+p.title} aria-pressed={selected===p.id} onClick={()=>{setSelected(p.id);setTimeout(()=>document.getElementById('selected-product')?.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'}),0);}}><ProductPhoto product={p}/><div className="product-card-title"><h3>{p.title}</h3><Icon name="arrow" size={18}/></div></button><div className="product-card-price"><strong>{money(accepted?acceptedQuote!.total_minor:p.price_minor)}</strong><span>{accepted?'Maximum per person':'Sandbox list price'}</span></div><p>{p.delivery_days}-day delivery</p>{accepted?<p className="card-group-progress">{count} of {acceptedQuote!.capacity} payments authorized</p>:a?<><p className={'fit-label '+(a.eligible?'fit-yes':'fit-unknown')}>{a.eligible?a.available>0?'Fits your request':'Currently unavailable':a.requirements.some(r=>r.verdict==='unknown')?'Required feature unknown':'Doesn’t fit'}</p><FitDetails assessment={a}/></>:<p className="card-group-progress">Find your group price</p>}</li>;})}</ul>{matches.length>0&&data&&data.assessments.some(a=>!a.eligible)&&<details className="excluded-products"><summary>Why {data.assessments.filter(a=>!a.eligible).length} other products didn’t fit</summary>{products.filter(p=>data.assessments.some(a=>a.product_id===p.id&&!a.eligible)).map(p=><div key={p.id}><h3>{p.title}</h3><FitDetails assessment={data.assessments.find(a=>a.product_id===p.id)!}/></div>)}</details>}</section>
  </main><StoreFooter/></div>;
}

interface Purchase { run_id:string;group_status:string;terms:Terms;capture_status:string|null;refund_status:string|null;void_status:string|null;authorization_status:string|null;active:boolean;captured_minor:number|null;created_at:string }
export function MyPurchases(){const [items,setItems]=useState<Purchase[]|null>(null),[error,setError]=useState(''),[config,setConfig]=useState<Config|null>(null);useEffect(()=>{void(async()=>{try{setConfig(await api('/config'));await api('/session',{run_id:new URLSearchParams(location.search).get('run')||undefined});setItems(await api('/purchases'));}catch{setError('We couldn’t load your purchases. Please try again.');}})();},[]);return <div className="shopping-page"><StoreHeader config={config}/><main className="purchase-history"><h1>My purchases</h1>{error?<p role="alert">{error}</p>:items===null?<p role="status">Loading your purchases…</p>:items.length?<ul>{[...items].sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(p=><li key={p.run_id}><div><h2>{p.terms.title}</h2><p>{p.refund_status==='COMPLETED'?'Refund confirmed':p.refund_status?'Refund in progress':p.void_status==='VOIDED'?'Authorization canceled':p.group_status==='SUCCEEDED'&&p.capture_status==='COMPLETED'?'Payment completed':p.capture_status==='COMPLETED'?'Resolving payment':p.group_status==='UNWINDING'?'Cancellation in progress':p.group_status==='SETTLING'?'Completing payments':p.authorization_status==='CREATED'?'Authorized · waiting for group':'Review payment status'}</p></div><strong>{money(p.captured_minor??p.terms.total_minor)}</strong><a href={'/checkout?run='+p.run_id}>View purchase<Icon name="arrow" size={16}/></a></li>)}</ul>:<><p>You haven’t joined a group purchase yet.</p><a className="coalition-button" href="/">Find a deal<Icon name="arrow" size={17}/></a></>}</main><StoreFooter/></div>;}
export function PricingHelp() {
  return <div className="request-page"><header className="request-header"><a href="/">Coalition</a></header><main className="pricing-help"><h1>How group pricing works</h1><ol><li>Review the exact product, delivery promise and maximum total. Approve that maximum through PayPal.</li><li>Wait for verified buyer commitments. You can leave before the fixed closing time. Shoppers need not stay on this page.</li><li>At closing, Coalition freezes the qualifying members and tier price. All selected payments must complete; otherwise completed captures are refunded and eligible holds voided.</li></ol><table><caption>Canonical small demo · approved maximum $89</caption><thead><tr><th>Valid authorizations at closing</th><th>Outcome</th></tr></thead><tbody><tr><td>Below 3</td><td>Cancel and unwind</td></tr><tr><td>3–4</td><td>Capture $89 per buyer</td></tr><tr><td>5</td><td>Capture $85 per buyer</td></tr></tbody></table><p>Your accepted quote supplies the actual tier schedule. A reached tier is provisional until closing. Pending approvals and expired holds do not count. Unknown captures and pending refunds stay visible until resolved.</p><p>Shipping is included; tax and fulfillment are simulated. One sandbox business account receives settlement. Bank hold release and refund availability follow provider and bank timing.</p><a href="/">Return to your request</a></main></div>;
}
